# -*- coding: utf-8 -*-
"""425hw6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UcXMsOCCD9ooDaKwE3Uyz506HJ-hJnQS
"""

from keras.datasets import mnist
(X_train, Y_train),(X_test, Y_test) = mnist.load_data()

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

X_train_0_9 = {'0':[],'9':[]}
Y_train_0_9 = {'0':[],'9':[]}
for i in range(len(Y_train)):
  if Y_train[i] == 0:
    X_train_0_9['0'].append(X_train[i])
    Y_train_0_9['0'].append(0)
  elif Y_train[i] == 9:
    X_train_0_9['9'].append(X_train[i])
    Y_train_0_9['9'].append(9)
X_test_0_9 = {'0':[],'9':[]}
Y_test_0_9 = {'0':[],'9':[]}
for i in range(len(Y_test)):
  if Y_test[i] == 0:
    X_test_0_9['0'].append(X_test[i])
    Y_test_0_9['0'].append(0)
  elif Y_test[i] == 9:
    X_test_0_9['9'].append(X_test[i])
    Y_test_0_9['9'].append(9)

print(len(X_train_0_9['0']))
print(len(Y_train_0_9['9']))
print(len(X_test_0_9['0']))
print(len(Y_test_0_9['9']))

from matplotlib import pyplot as plt
plt.figure()
plt.imshow(X_train_0_9['9'][0],cmap='gray')
plt.show()

from cvxopt import matrix, solvers
Q = 2*matrix([ [2, .5], [.5, 1] ])
p = matrix([1.0, 1.0])
G = matrix([[-1.0,0.0],[0.0,-1.0]])
h = matrix([0.0,0.0])
A = matrix([1.0, 1.0], (1,2))
b = matrix(1.0)
sol=solvers.qp(Q, p, G, h, A, b)
print(sol['x'])

print(Q)

